 Name: Jeet Patel ||
 Roll No: 24BCE085 ||
 Batch: B2 ||
 Practical No.: 4



In [1]:
import pandas as pd
import time

mat = pd.read_csv("6citytsp.csv",header=None).values

print(mat)
print(mat.dtype)

[[  0  64 378 519 434 200]
 [ 64   0 318 455 375 164]
 [378 318   0 170 265 344]
 [519 455 170   0 223 428]
 [434 375 265 223   0 273]
 [200 164 344 428 273   0]]
int64


In [2]:
#Brute Force

from itertools import permutations
import numpy as np

citynames = list(range(mat.shape[0]))
per = permutations(citynames)
print(type(per))
per = list(per)
print(type(per))
print(per)
print()

st = time.process_time()
print(st)
besttourlength = np.inf

for tour in per:
    tourlength = 0
    for i in range(len(tour)-1):
        tourlength += mat[tour[i],tour[i+1]]
    tourlength += mat[tour[i+1],tour[0]]
    
    if tourlength < besttourlength:
        besttourlength = tourlength
        besttour = tour

et = time.process_time()
time_taken_ms = (et-st)*1000
print("Best Tour:", besttour)
print("Best Tour's Length:", besttourlength)
print("Time Taken: ", time_taken_ms)

<class 'itertools.permutations'>
<class 'list'>
[(0, 1, 2, 3, 4, 5), (0, 1, 2, 3, 5, 4), (0, 1, 2, 4, 3, 5), (0, 1, 2, 4, 5, 3), (0, 1, 2, 5, 3, 4), (0, 1, 2, 5, 4, 3), (0, 1, 3, 2, 4, 5), (0, 1, 3, 2, 5, 4), (0, 1, 3, 4, 2, 5), (0, 1, 3, 4, 5, 2), (0, 1, 3, 5, 2, 4), (0, 1, 3, 5, 4, 2), (0, 1, 4, 2, 3, 5), (0, 1, 4, 2, 5, 3), (0, 1, 4, 3, 2, 5), (0, 1, 4, 3, 5, 2), (0, 1, 4, 5, 2, 3), (0, 1, 4, 5, 3, 2), (0, 1, 5, 2, 3, 4), (0, 1, 5, 2, 4, 3), (0, 1, 5, 3, 2, 4), (0, 1, 5, 3, 4, 2), (0, 1, 5, 4, 2, 3), (0, 1, 5, 4, 3, 2), (0, 2, 1, 3, 4, 5), (0, 2, 1, 3, 5, 4), (0, 2, 1, 4, 3, 5), (0, 2, 1, 4, 5, 3), (0, 2, 1, 5, 3, 4), (0, 2, 1, 5, 4, 3), (0, 2, 3, 1, 4, 5), (0, 2, 3, 1, 5, 4), (0, 2, 3, 4, 1, 5), (0, 2, 3, 4, 5, 1), (0, 2, 3, 5, 1, 4), (0, 2, 3, 5, 4, 1), (0, 2, 4, 1, 3, 5), (0, 2, 4, 1, 5, 3), (0, 2, 4, 3, 1, 5), (0, 2, 4, 3, 5, 1), (0, 2, 4, 5, 1, 3), (0, 2, 4, 5, 3, 1), (0, 2, 5, 1, 3, 4), (0, 2, 5, 1, 4, 3), (0, 2, 5, 3, 1, 4), (0, 2, 5, 3, 4, 1), (0, 2, 5, 4, 1, 3), (0, 2, 5, 4

In [3]:
#TSP using Nearest Neighbour Heuristic, not always optimal
import pandas as pd
import numpy as np
import time

mat = pd.read_csv("11citytsp.csv",header=None).values.astype(float)

startcity = int(input("Enter Starting City from 0 to "+str(mat.shape[0]-1) + ":"))
st = time.process_time()
tourlength = 0
besttour = [startcity]
mat[mat==0] = np.inf
print(mat)

matorigcopy =  mat.copy()

for i in range(mat.shape[0]-1):
    if i==0:
        tourlength += min(mat[startcity,:])
        nextbestind = int(np.argmin(mat[startcity,:]))
        besttour.append(nextbestind)
        mat[:,nextbestind] = np.inf
        mat[:,startcity] = np.inf
    else:
        tourlength += min(mat[nextbestind,:])
        nextbestind = int(np.argmin(mat[nextbestind,:]))
        mat[:,nextbestind]=np.inf
        besttour.append(nextbestind)

tourlength += matorigcopy[nextbestind,startcity]
et = time.process_time()
time_taken_ms = (et - st)*1000
print("Best Tour:", besttour)
print("Best Tour's Length:", tourlength)
print("Time Taken: ",time_taken_ms)

[[ inf 633. 257.  91. 412. 150.  80. 134. 259. 505. 353.]
 [633.  inf 390. 661. 227. 488. 572. 530. 555. 289. 282.]
 [257. 390.  inf 228. 169. 112. 196. 154. 372. 262. 110.]
 [ 91. 661. 228.  inf 383. 120.  77. 105. 175. 476. 324.]
 [412. 227. 169. 383.  inf 267. 351. 309. 338. 196.  61.]
 [150. 488. 112. 120. 267.  inf  63.  34. 264. 360. 208.]
 [ 80. 572. 196.  77. 351.  63.  inf  29. 232. 444. 292.]
 [134. 530. 154. 105. 309.  34.  29.  inf 249. 402. 250.]
 [259. 555. 372. 175. 338. 264. 232. 249.  inf 495. 352.]
 [505. 289. 262. 476. 196. 360. 444. 402. 495.  inf 154.]
 [353. 282. 110. 324.  61. 208. 292. 250. 352. 154.  inf]]
Best Tour: [3, 6, 7, 5, 2, 10, 4, 9, 1, 8, 0]
Best Tour's Length: 1813.0
Time Taken:  0.0
